---
title: "Quão justa é a percepção sobre a distribuição de renda entre os países da América Latina?"
date: "08-04-2024"
author:
   name: Dan Nogueira da Silva
   email: dan.nogueira@ufrj.br
abstract: O presente trabalho tem como objetivo analisar a relação entre a percepção de desigualdade entre os cidadãos latino-americanos e a desigualdade real medida pelo índice de Gini. Utilizando dados do Latinobarómetro e o índice de Gini de cada país, buscamos entender como a percepção subjetiva de desigualdade se alinha ou diverge da desigualdade econômica objetiva.
format:
  pdf:
    toc: false
    number-sections: false
    colorlinks: true
    fig-pos: 'H'
    geometry:
      - top=25mm
      - left=20mm
      - right=20mm
      - bottom=25mm
lang: pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

# Pacotes
library(tidyverse)
library(rio)
```

# Dados utilizados

-   **Latinobarómetro** ➜ Pesquisa de opinião pública latino-americana.

Ferramenta fundamental para entender as dinâmicas sociais, políticas e econômicas da América Latina, com o objetivo mapear as opiniões, valores e comportamentos da população.

A pesquisa é realizada anualmente em cerca de 20 países da América Latina, envolvendo um grande número de entrevistas face a face. Todos os entrevistados respondem às mesmas perguntas, o que permite a comparação dos resultados entre os diferentes países.

-   **Índice de Gini** ➜ indicador utilizado para analisar a desigualdade social em diversos países e regiões.

Ferramenta estatística utilizada para medir o grau de desigualdade na distribuição de renda ou de outros recursos em uma determinada população.

O Índice de Gini mede a área entre a linha de perfeita igualdade e a curva de Lorenz. Quanto maior essa área, maior a desigualdade. O índice varia de 0 a 1:

> **0:** Indica perfeita igualdade (todos têm a mesma renda).
>
> **1:** Indica máxima desigualdade (uma única pessoa possui toda a renda).

# Metodologia

As variáveis de percepção de desigualdade foram extraídas para os anos 2015-2018 em 16 países da América Latina.

Os valores do índice de Gini foram utilizados para os mesmos anos e países.

Excluímos Espanha, Guatemala e Nicarágua da análise pois não encontramos o índice de Gini correspondente para todos os anos em que a pergunta de nosso interesse foi feita.

Após a limpeza e preparação dos dados, realizamos análises descritivas e de correlação, seguidas por modelagem estatística para investigar a relação entre as variáveis.
